### ISSUE TITLE
List of all Countries #1

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#1]
#### Value Proposition

**As a** Travel Enthusiast

**I want to** see a list of all countries

**so that** I can get an overview of all countries

![Image](https://user-images.githubusercontent.com/123647583/229136384-81d3a3bb-4235-4876-8478-1ff54f8194d0.png)

#### Acceptance Criteria

- [X] All country names are displayed as a list 🌍
- [X] A header with a headline  is displayed 
- [X] Country list is sorted by alphabet

#### Tasks

- [X] useSWR to fetch data from: https://restcountries.com/v3.1/all
- [X] create the page /list which renders the Component `CountryList` and `Header`
- [X] create a dummy Link on index.js that leads to the list page
- [X] Create the component `CountriesList` to render a list
- [X] Create the component `Header` with props `headline`
- [X] All acceptance criteria marked with 🌍 are covered by component testing

#### Complexity
S

**Comment by PacoSchwab** [comment]
Looks so beautiful to me 👍

**Comment by Satttoshi** [comment]
lgtm

**Comment by Satttoshi** [comment]
whoops there is an issue wait
