### ISSUE TITLE
Local storage #7

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#13]
#### Value Proposition

**As a** travel enthusiast

**I want** the favorite/visited countries and the counter to be saved constantly

**so that** I won't have to mark everything agin when re-loading the page

![Image](https://user-images.githubusercontent.com/123647583/230591979-33b2395e-ebf1-4d74-9552-199b2f61076e.png)

#### Acceptance Criteria

- [X] all marked countries (visited + favorite) and the counter are saved in local storage

#### Tasks

- [X] import the `useLocalStorageState`
- [X] amend the `useState` to `useLocalStorage`

**Comment by augustinanders** [comment]
Looks good to me.
