### ISSUE TITLE
Search bar #8

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#14]
#### Value Proposition

**As a** travel enthusiast

**I want** to use a search bar in the countries list view

**so that** I won't have to scroll down the whole page to search for a country

![Image](https://user-images.githubusercontent.com/123647583/230595775-1b76c327-a9fd-4aaa-82b3-4ca37ddcf48e.png)

#### Acceptance Criteria

- [X] a Search bar is displayed
- [X] the search bar lets the user filter through the countries when typing 

#### Tasks

- [X] create the component `Search Bar`
- [X] render the `Search bar` on the `list` page
- [X] Add an OnChange event to the Search bar

**Comment by augustinanders** [comment]
Maybe also include functionality to your acceptance criteria. Otherwise your `search-bar` is useless.

**Comment by PacoSchwab** [comment]
LGTM!
![18-10-28_0002-sea-otter-BB-web-1024x512](https://user-images.githubusercontent.com/124581406/230650209-471506e6-80fc-477d-a29d-c760bf5af40a.jpg)
