### ISSUE TITLE
Counter per continent #9

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#16]
**As a** travel enthusiast

**I want to** see a counter of visited countries per continent

**so that** I will have an overview of how many countries per continent I have visited so far

![Image](https://user-images.githubusercontent.com/123647583/230616588-de004d7c-d30f-4272-af3f-3b57645cc33f.png)

- [X] A Counter per continent is displayed
- [X] the Counter displays the amount of countries that have been visited per continent

#### Tasks

- [X] Create the component `CounterContinent` with prop `continent`
- [X] Render the component `CounterContinent` on pages/index.js for each continent

**Comment by augustinanders** [comment]
LGTM! You could add a gamification aspect later. Like achievements. 
also you could add a `progess-bar` later:
<img width="203" alt="Screenshot 2023-04-09 at 09 59 19" src="https://user-images.githubusercontent.com/121796762/230761363-49f7f40c-2984-4232-9cdc-90eacb44c60a.png">

**Comment by AnjaSiewert** [comment]
That's a great idea, thanks a lot! :)
