### ISSUE TITLE
Details page #11

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#18]
#### Value Proposition

**As a** travel enthusiast

**I want to** see a details countries page

**so that** I will have more information about the respective country

![Image](https://user-images.githubusercontent.com/123647583/230729710-e53c8537-fec7-4560-a288-ba1665645d2f.png)

#### Acceptance Criteria

- [X] One detail page for each country is displayed
- [X] Each card contains: `country`, `continent`,`capital`, `flag`, `inhabitants`, `language`, `timezone`
- [X] Each card displays the respective countries flag
- [X] clicking on the country name on the list page leads to the respective details page 
- [X] A back button is displayed to navigate to the previous page
- [X] A header is displayed

#### Tasks

- [X] Render the Component `CountryDetails`
- [X] Create the page pages/[name] that renders the component `CountryDetails`
- [X] add useRouter for Navigation through the pages 
- [X] Add a back Button which leads to the previous page
- [X] on component `CountriesList` a link routes to the respective details page when clicking on the countries name

**Comment by Kevinwey** [comment]
LGTM!
