### ISSUE TITLE
Visited bookmark #2

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#2]
#### Value Proposition

**As a** travel enthusiast

**I want to** have the possibility to mark countries as visited

**so that** I have an overview of countries I have been to

![Image](https://user-images.githubusercontent.com/123647583/229138428-33d2edca-5663-48a9-8621-93fd78b640b1.png)

#### Acceptance Criteria

- [X] The visited-bookmark is displayed in the list page 🌍
- [X] Clicking the visited-bookmark on a non-visited country saves it as a visited country 🌍
- [X] Clicking the visited-bookmark on a visited country removes it from visited countries 🌍

#### Tasks

- [X] Create a state `countriesInfo` to save further information for countries
- [X] Make the `countriesInfo` state globally available for all pages
- [X] Store the visited flag in the `countriesInfo`
- [X] Create the component `VisitedButton`
- [X] import an SVG Icon to use as a visited Bookmark
- [X] `VisitedButton` props: `isVisited`, `onToggleVisited`
- [X] write the function `handleToggleVisited`
- [X] Render the `VisitedButton` component in the `CountriesList` component
