### ISSUE TITLE
Progress bar Counter #12

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#21]
**As a** travel enthusiast

**I want to** see a progress bar on the visited countries per continent card

**so that** I will have an visual overview of my progress 

![Image](https://user-images.githubusercontent.com/123647583/231120103-15f749c2-ae08-440a-9094-70f056815c2e.png)

- [ ] one progress bar per continent is displayed
- [ ] the progress bar increases and decreases with the amount of countries marked as visited

#### Tasks

- [ ] Create the component `ProgressBar`
- [ ] Render the component `Progressbar` on pages/index.js for each continent

**Comment by AnjaSiewert** [comment]
**As a** travel enthusiast

**I want to** see a progress bar on the visited countries per continent card

**so that** I will have an visual overview of my progress 

![Image](https://user-images.githubusercontent.com/123647583/231120103-15f749c2-ae08-440a-9094-70f056815c2e.png)

- [ ] one progress bar per continent is displayed
- [ ] the progress bar increases and decreases with the amount of countries marked as visited

#### Tasks

- [ ] Create the component `ProgressBar`
- [ ] Render the component `Progressbar` on pages/index.js for each continent
