### ISSUE TITLE
Progress bar Counter #12

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#22]
**As a** travel enthusiast

**I want to** see a progress bar on the visited countries per continent card

**so that** I will have an visual overview of my progress 

![Image](https://user-images.githubusercontent.com/123647583/231120103-15f749c2-ae08-440a-9094-70f056815c2e.png)

- [X] one progress bar per continent is displayed
- [X] the progress bar increases and decreases with the amount of countries marked as visited

#### Tasks

- [X] Create the component `ProgressBar`
- [X] Render the component `Progressbar` on pages/index.js for each continent
- [X] use width in CSS to edit the progress accordingly

**Comment by Kevinwey** [comment]
LGTM!
