### ISSUE TITLE
Adding a form for own entries #13

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#23]
**As a** travel enthusiast

**I want to** be able to add details to the countries I want to visit

**so that** it will help me plan my future trips

![Image](https://user-images.githubusercontent.com/123647583/231180785-2ba7e3a7-1d7f-4aa5-b4ba-5757ce0f87ef.png)

- [X] on favorite page a form with a submit button is displayed for every favorite country card
- [X] the form should have 2 input fields: `When do I want to go?`,`approx. budjet`, `allowed days (visa)`
- [X] the form should have 3 checkboxes with yes and no option: `Visa required?`, `Vaccination required?`, `passport required`
- [X] the form should have one textarea field: `Notes`

#### Tasks

- [X] Create the component `Form` with input fields, checkboxes, textarea and a submit button
- [X] Render the component `Form` +  the submit button on pages/favorites

**Comment by PacoSchwab** [comment]
Beautiful!
