### ISSUE TITLE
Submit the form data #14

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#24]
**As a** travel enthusiast

**I want to** be able to see the details I added to the countries I want to visit

**so that** it will help me plan my future trips

![Image](https://user-images.githubusercontent.com/123647583/231185120-689fd6c5-f525-45e8-b3fe-f9e647d6971d.png)

- [X] a button `Plan my trip` is displayed on favorites page i.o. form 
- [X] the form only appears when clicking on the button "Plan my trip"
- [X] upon submitting the form , the input data it is displayed on the card 

#### Tasks

- [X] Create the function `handleSubmitForm` 
- [X] add a functionality to show the form when the button is clicked
