### ISSUE TITLE
Editing own entries #16

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#25]
**As a** travel enthusiast

**I want to** be able to edit the details I added to the countries I want to visit

**so that** I can keep my travel itinerary up-to-date

![Image](https://user-images.githubusercontent.com/123647583/231193181-1a0cf420-5a14-4e2b-a402-3a4e405a9e53.png)

- [X] an `Edit` button is displayed on favorites page
- [X] details can be edited when pushing this button
- [X] upon saving the amendments the new details are displayed

#### Tasks

- [X] Create the function `handleEditEntry`

**Comment by augustinanders** [comment]
LGTM! 🚀
One Suggestion: Does the form Look the same like the details-page? I would write: When pushing this button again you are switching to the form again, to make changes.

**Comment by AnjaSiewert** [comment]
Thanks for your comment! The details page is another page and does not look the same. 
This form is rendered on the favorites page
