### ISSUE TITLE
Deleting own entries #17

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#26]
**As a** travel enthusiast

**I want to** be able to delete the details I added to the countries I want to visit

**so that** I can keep my travel itinerary up-to-date

![Image](https://user-images.githubusercontent.com/123647583/231195320-8f7a194a-acc8-48d9-a6e7-e24316ea22c7.png)

- [X] a `Delete` button is displayed on favorites page
- [X] details are deleted when pushing this button

#### Tasks

- [X] Create the function `handleDeleteEntry`

**Comment by toshydev** [comment]
LGTM✅️
