### ISSUE TITLE
Visited page #3

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#3]
#### Value Proposition

**As a** travel enthusiast

**I want to** see a visited countries page

**so that** I will have an overview of all countries I have been so far

![Image](https://user-images.githubusercontent.com/123647583/229301444-37bb6db4-9560-4ed3-b9e9-87f391816bbf.png)

#### Acceptance Criteria

- [X] One card for each visited country is displayed
- [X] Each card contains: `country`, `continent`,`capital`, `flag`
- [X] Each card displays the respective countries flag
- [X] The visited-bookmark SVG is displayed in the visited page 🌍
- [X] Clicking the visited-bookmark on a non-visited country saves it as a visited country on page visited 🌍
- [X] Clicking the visited-bookmark on a visited country removes it from visited countries on page visited 🌍
- [X] A header is displayed

#### Tasks

- [X] Create the component `CountriesPreview`
- [X] Create the page pages/visited that renders the component `CountriesPreview`
- [X] `CountriesPreview` props: `country`, `continent`, `capital`, `flag`,`isVisited`
- [X] render the Component `VisitedButton` on `CountriesPreview` component
- [X] render the `Header` Component on `visited` page

**Comment by Lutz-Dietterich** [comment]
nice user story, i just have a small question, is the visited-bookmark component already available or does it still have to be created?

**Comment by AnjaSiewert** [comment]
The visited bookmark will be an SVG - I added it in the US. Thanks for your comment!
