### ISSUE TITLE
Add continents filter on Searchbar #19

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#33]
#### Value Proposition

**As a** travel enthusiast

**I want** to be able to filter for continents in the countries list view

**so that** I will be able to mark countries as visited and favorite faster on first attempt

![Image](https://user-images.githubusercontent.com/123647583/232577511-b4922909-2adf-4b33-b0ee-c209c49e947a.png)

#### Acceptance Criteria

- [X] There is an option to filter for all continents displayed on the list page
- [X] When filtering for a continent, only the respective countries for that continent are displayed

#### Tasks

- [X] add a filter option to the list page

**Comment by toshydev** [comment]
LGTM✅️
