### ISSUE TITLE
Sort favorites and visited countries #18

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#36]
**As a** travel enthusiast

**I want to** see the visited and favorite countries sorted alphabetically 

**so that** I can easily navigate through the entries

![Image](https://user-images.githubusercontent.com/123647583/232723956-8a0ea552-6598-4818-99ed-7dd47eaf0b52.png)

#### Acceptance criteria

- [X] The visited countries are sorted alphabetically
- [X] The favorite countries are sorted alphabetically

#### Tasks

- [X] insert the .sort() method on the `favorite` page
- [X] insert the .sort() method on the `visited` page

**Comment by toshydev** [comment]
LGTM ✅

**Comment by Stephan-mit-Ph** [comment]
work as expected 🏝️
