### ISSUE TITLE
Navigation Bar #4

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#4]
#### Value Proposition

**As a** travel enthusiast

**I want to** be able to switch between the pages

**so that** I can navigate easier between the pages of the app

![Image](https://user-images.githubusercontent.com/123647583/229152482-f2128d05-321a-45e6-b4e7-d7bac200d154.png)

#### Acceptance Criteria

- [X] A navigation link shown with Location Icon is displayed 🌍
- [X] A navigation link shown with List Icon is displayed 🌍
- [X] Clicking the Location Icon shows the visited page
- [X] Clicking the List Icon shows the list page

#### Tasks

- [X] Create the component `Layout` that renders the `Navigation` component
- [X] Import SVGs to display the Icons
- [X] Apply the `Layout` component in `pages/_app`
