### ISSUE TITLE
Progress bar Total #21

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#42]
**As a** travel enthusiast

**I want to** see a progress bar on the visited countries overall

**so that** I will have an visual overview of my progress all over the world

![Image](https://user-images.githubusercontent.com/123647583/233947550-9049b686-b739-4b8e-8311-3b9dc154403e.png)

- [X] one progress bar for the total amount of all countries is displays
- [X] the progress bar increases and decreases with the amount of countries marked as visited

#### Tasks

- [X] Update the existing component `Counter`
- [X] use the StyledProgressBar

**Comment by FrankSiyli** [comment]
LGTM
