### ISSUE TITLE
Worldmap SVG

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#44]
#### Value Proposition

**As a** travel enthusiast

**I want ** the visited countries to change to another color when they are marked as visited
**so that** I have a visual overview of countries I have been to

![Image](https://user-images.githubusercontent.com/123647583/234201772-8838946c-14b4-4d25-8581-1e208c070892.png)

#### Acceptance Criteria

- [ ] An SVG worldmap is displayed on the homepage
- [ ] When marking a country as visited the respective country is displayed in another color

#### Tasks

- [ ] Use the state `countriesInfo` where the `isVisited` status is saved

- [ ] Create the component `CountryColorChange`
- [ ] import an SVG Image with all countries displayed
- [ ] `CountryColorChange` props: `isVisited`, `onToggleColorChange`
- [ ] write the function `handleToggleColorChange`
- [ ] Render the `CountryColorChange` component on the homepage
