### ISSUE TITLE
Write Tests #24

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#48]
#### Value Proposition

**As a** developer
**I want to** write tests to ensure that my components work properly
**so that** potential issues can identified on an early stage

#### Acceptance criteria

- [X] write at least four tests to cover the main functions

#### Tasks

- [X] write tests with jest
- [X] all tests are passing
