### ISSUE TITLE
Accessibility #23

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#49]
#### Value Proposition

**As a** user with accessibility needs
**I want to** be able to use the app easily
**so that** I can fully access and utilize all features of the app

#### Tasks

- [X] aria-labels are provided if needed
- [X] lang attribute is set
- [X] check lighthouse report scores
