### ISSUE TITLE
Homepage #5

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#5]
#### Value Proposition

**As a** travel enthusiast

**I want to** see a homepage with a counter

**so that** I will have an overview of the amount of countries I have travelled to

![Image](https://user-images.githubusercontent.com/123647583/229302125-cd2ba114-5a05-44d3-8e67-8ed51da1f6ae.png)

#### Acceptance Criteria

- [X] An image of the world map is displayed
- [X] A Counter is displayed
- [X] A header is displayed

#### Tasks

- [X] Create the component `Counter`
- [X] Render the component `Counter` on pages/index.js
- [X] Render the `Header` Component on `index.js`
- [X] Add an Link to this page on the `Navigation` Component
- [X] Display an HomeIcon in the NavBar

**Comment by WE-Kaito** [comment]
Nice user story!
