### ISSUE TITLE
Favorites page #6

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#6]
#### Value Proposition

**As a** travel enthusiast

**I want to** see a favorite countries page

**so that** I will have an overview of all countries I want to explore

![Image](https://user-images.githubusercontent.com/123647583/230349794-54f339ab-8708-4b8c-825f-00792f7358e0.png)

#### Acceptance Criteria

- [X] One card for each country that I want to visit (again) is displayed
- [X] Each card contains: `country`, `continent`,`capital`, `flag`
- [X] Each card displays the respective countries flag
- [X] The visited-bookmark is displayed in the visited page 🌍
- [X] Clicking the visited-bookmark on a non-visited country saves it as a visited country on page visited 🌍
- [X] Clicking the visited-bookmark on a visited country removes it from visited countries on page visited 🌍
- [X] A header is displayed

#### Tasks

- [X] Render the Component `CountriesPreview`
- [X] Create the page pages/favorites that renders the component `CountriesPreview`
- [X] render the Component `FavoriteButton` on `CountriesPreview` component
- [X] Add an Link to this page on the `Navigation` Component
- [X] Display an FavoriteIcon in the NavBar

**Comment by Stephan-mit-Ph** [comment]
🌏🚀💥
